### ISSUE TITLE
[Feature] Add specific characteristics to quest requirements

### ISSUE THREAD

**Issue by cyber01** [NicJames2378/BQ-Forestry#5]
You can expand the conditions for quests. To receive not only a drone / princess / queen, but also bees with certain characteristics (number of offspring, speed of work, nocturnal, flowers, etc.)

This would allow very flexible customization of quests for butterflies / trees / bees.

**Comment by NicJames2378** [comment]
Bee Traits:
```
			0 Species
				SPECIES
			1 Speed
				SPEED
			2 Lifespan
				LIFESPAN
			3 Fertility
				FERTILITY
			4 Tolerance
				TEMPERATURE_TOLERANCE
			5 BoolFalse
				NEVER_SLEEPS
			6 Tolerance
				HUMIDITY_TOLERANCE
			7 BoolFalse
				TOLERATES_RAIN
			8 BoolFalse
				CAVE_DWELLING
			9 Flowers
				FLOWER_PROVIDER
			10 FloweringSpeed
				FLOWERING
			11 TerritorySize
				TERRITORY
			12 Effect
				EFFECT
```

Should I allow multiple of each to be selected, or only a single per?

**Comment by cyber01** [comment]
I think you can make a list because bees can even have all abilities in the game

**Comment by NicJames2378** [comment]
Note: This is simply a status update. There is no need to reply.

It's been a difficult run, but I have yet to find a stable way to support multiple species for a single bee due to the way Forestry handles (and overwrites) it's NBTs. I will move on to trying to get it working with the other traits. My apologies for the delays on this update.

**Comment by NicJames2378** [comment]
This functionality has been officially implemented for most of the alleles (Flower_Provider and Effect still a WIP). A beta build is going up on CurseForge now (1.1.3b)

**Comment by NicJames2378** [comment]
A public release is not yet available, but this is officially implemented (Flower Providers and Effects included!) in the new GUI. I am trying to release version 2.0 of the mod in the next couple weeks. Marking this as closed now :D
