### ISSUE TITLE
[1.12.2] 1.12.2 FTB Utilities Server Crash & bqforestry-1.1.3b

### ISSUE THREAD

**Issue by MokahTGS** [NicJames2378/BQ-Forestry#7]
Getting a server crash on the new version.

Forge 2847
FTB Util 5.4.0.107
bqforestry-1.1.3b
Crash log: https://pastebin.com/xW26NPDq

Full mod list: https://pastebin.com/xZb8nTjg

https://github.com/FTBTeam/FTB-Utilities/issues/1042

**Comment by NicJames2378** [comment]
The issue was a piece of code calling for a client only method. It should be resolved in 1.1.3.2b, going up on CurseForge now. Let me know if your issue is resolved!

**Comment by MokahTGS** [comment]
Thx, I'll let you know
